-- Replicas --
replica0 130.245.173.101
replica1 130.245.173.103
replica2 130.245.173.104
replica3 130.245.173.125
replica4 130.245.173.126

-- Clients --
client0 130.245.173.101
client1 130.245.173.103
client2 130.245.173.104

-- Master --
master0 130.245.173.103

masterPort: 7087

protocol: curp
maxDescRoutines: 500
batchDelayUs: 150

noop:       false
thrifty:    false
fast:       true

reqs:        3000
writes:      5
conflicts:   0
commandSize: 100
clientThreads: 32
pipeline:    true
pendings:    15

weakRatio:   0
weakWrites:  5

networkDelay: 25

keySpace:    1000000
zipfSkew:    0

-- Proxy --
server_alias replica0
client0 (local)
server_alias replica1
client1 (local)
server_alias replica2
client2 (local)
---
