-- Replicas --
replica0 127.0.0.1
replica1 127.0.0.2
replica2 127.0.0.3

-- Clients --
client0 127.0.0.4

-- Master --
master0 127.0.0.1

masterPort: 7087

protocol: epaxosho

// Replica settings
noop:       false
thrifty:    false
fast:       false

// Client settings
reqs:        1000
writes:      50       // 50% writes
conflicts:   0
commandSize: 100
clones:      0

// Hybrid benchmark settings
weakRatio:   50       // 50% weak, 50% strong
weakWrites:  50       // 50% of weak commands are writes

-- Proxy --
server_alias replica0
client0 (local)
---
